### ISSUE TITLE
Review cloud.gov "production ready" checklist

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1158]
We have many of the items on https://cloud.gov/docs/deployment/production-ready/ let's make sure we have all the rest of them.

**Comment by neilmb** [comment]
- [X] Configuration as code
- [ ] More than one instance: #1151 
- [X] Protect access to sensitive credentials
 
I reviewed the SpaceDevelopers on the stable space and there is a reasonable set of developers listed there right now. If we want to minimize it, we could take almost everyone away, but I don't think that we need to be any more restrictive.

- [X] Prefer dedicated over shared services
- [X] Space per environment
- [X] Prevent non-auditable changes to production apps

I turned off SSH access to the `stable` space. If debugging requires it to be re-enabled, then any SpaceDeveloper can issue `cf allow-space-ssh stable`. Ideally in `stable` all code changes would be made through appropriate Github deploys.
      
- [ ] Zero downtime deploy #1151 
- [X] Automated deployments
- [ ] Caching: ???
- [ ] Asset serving: ???
- [ ] Custom domain name #1159
- [X] Graceful shutdown: as far as I know, this is taken care of by Python/Django

**Comment by neilmb** [comment]
I made #1170 to track the two remaining question marks from this list that don't already have tickets.

**Comment by neilmb** [comment]
Multiple instances and zero-downtime deploys are both running on stable now.
