### ISSUE TITLE
(3) [ EPIC ] Figma file updates: Update Registrar/Forms Base Pages 

### ISSUE THREAD

**Issue by rileyorr** [cisagov/manage.get.gov#1971]
**Update from Aug 2024 Audit** 

### Issue description

The audit form Aug 2024 found that the Registar - get.gov/manage/forms base pages do not match production or are missing.  Base pages are mockups of production pages so that designers can use for new feature updates without having to recreate the "base" for every new update. 

Now that the design system component updates have been complete, these pages can be updates.  
Notes on what needs to be updates are made directly in the Figma file. 

The work will be broken up into multiple issues one for each page for easier Figma implementation. The pages with their story links are listed below:

- [ ] Form/preamble - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=4289-51265&m=dev)  
- [ ] Form/Registrar request form - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=2211-25394)
- [ ] Form/org type  - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=4131-37547)
-  [ ] Form/conditional/Fedbranch- [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=2996-5206)
- [ ] Form/conditional/ElectionOffice  - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=155-53846)  
- [ ] Form/Conditional/TribalGovernment - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=144-42920)
- [ ] Form/Organizational name and mailing  - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=4131-38045)
- [ ] Form/Conditional/AboutOrg -[ Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=3095-63508)
- [ ] Form/AuthOfficial  - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=3003-7987)
- [ ] Form/Conditional/Seniorofficial - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8201-12302)
- [ ] Form/currentWebsites - [Figma page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=3046-101483)
- [ ] Form/.govDomains [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=4131-37771)
- [ ] Form/purpose - [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=4131-38223) 
- [ ] Form/Otheremployeesfromyourorg - [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=392-6055)
- [ ] Form/additionaldetails - [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=3193-108070)
- [ ] Form/requirements -[ Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=3057-101716)
- [ ] form/review - [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=2703-31376)
- [ ] Form/confirmation - [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=2842-32296)
- [ ] Form/Review submitted request - [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=4052-19169)
- [ ] Form request email confirmation [Figma Page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8162-11349)

### Acceptance criteria
- [ ] Figma Registrar Form base page matches production
- [ ] Update the [Registrar cover page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8193-9457)
- [ ] Update the[ Registrar read me page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8155-37616)
- [ ] Create/update a local "Registrar component" page and centralize local components 
- [ ] Auto-layout is used when possible.
- [ ] Layers are organized and named
- [ ] Design system components and styles are used when possible
- [ ] Changes are made in a Figma branch and are reviewed by another designer
- [ ] Changes are merged

### Additional context
- Try to get these done by the end of the year to make sure audit changes dont become outdated
- Some of the issues will only take a few minutes

### Links to other issues
This work is blocked by all Figma Design System stories. 

Issues that relate to this Epic are:

- #2788 
- #2789 
- #2790 
- #2791 
- #2792 
- #2793 
- #2794 
- #2795 
- #2796 
- #2797 
- #2798 
- #2799 
- #2800 
- #2801 
- #2802 
- #2803 
- #2804 
- #2805 
- #2806 
- #2807 
- #2808 
-

**Comment by joet333** [comment]
Updated to reflect Audit from Aug 2024.
