### ISSUE TITLE
Shorten PR checklist template

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2140]
### Issue description

Shorten PR checklist template.  Review checklist and identify elements for removal to streamline the template for efficiency. However, we want 

### Acceptance criteria

- [x] review checklist and identify elements for removal to streamline the template for efficiency
- [ ] discuss proposed updates to the checklist template with the team
- [x] update checklist template 
- [x] Make a PR review section of our readmes that talks about our best practices and be sure to include the main steps of the current checklist (see additional context)
~[ ] Update the PR template title to the following: (draft/ignore) #0000: Description - [env]~
- [ ] Add a note regarding our new PR naming scheme. [Specified here](https://docs.google.com/document/d/16S6VNKOYW2HI7bKwOwOdQzon5SZA0ZgkMkGfQHLZoTw/edit#heading=h.nydvw91i6kl).

### Additional context
When adding the PR review section to our readmes, this is to preserve our current best checklist for future developers that may onboard at another time. That said, you don't need repeat all the steps that duplicate for original developer, design reviewer and design reviewer
Please wait until additional engineers/devs have onboarded, approximately July 2024.

Removed the title AC because GitHub currently does not support customizing template titles for PRs (though it does for issues). Can keep an eye on [this issue on GitHub support](https://github.com/isaacs/github/issues/1252).

**Comment by vickyszuchin** [comment]
Per action item from eng huddle.

**Comment by PaulKuykendall** [comment]
https://github.com/weather-gov/weather.gov/pull/279#issuecomment-1759959083 has an interesting process.

**Comment by PaulKuykendall** [comment]
@abroddrick - please wordsmith this and move to Ready at your discretion.

**Comment by abroddrick** [comment]
Already did!

**Comment by rileyorr** [comment]
Hey all! Just dropping by to mention that I created [a ticket to synthesize the accessibility survey findings](https://github.com/orgs/cisagov/projects/26/views/27?pane=issue&itemId=63611986) that may influence some updates made to the PR checklist template as part of this ticket. 

cc @gabydisarli @Katherine-Osos

**Comment by gabydisarli** [comment]
During our design sync on May 21st, we discussed introducing a new process for how we'll track when issues have bypassed the design phase. We decided that we should add an item to the PR checklist that has something along the lines of:

> check with design to make sure the work to update the figma and content docs is documented (should only apply to issues with the "design-artifact-update" label. 

cc: @vickyszuchin

**Comment by h-m-f-t** [comment]
I raised this higher in the backlog.
