### ISSUE TITLE
Design: Hi-Fidelity mockups of the domain request management experience for Org admins 

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2206]
### Issue description

Create hi-fidelity wireframes for Org admins to view and manage domain requests. This flow covers the ability for an org admin to hide domain requests and filter them based on agreed filters. Additionally, this should show how domain requests are automatically hidden if they are older than a certain time frame ie. 90 days and should show how org admins can expand the hidden requests. Org admins can also click into a historical page of all domain requests for the organization.

### Acceptance criteria

**Create hi-fi mockups for**
- [x] domain requests page
- [x] ~domain request history/archive page~ (This AC was removed after discussion with product)

**Create prototype for**
- [x] ~Withdrawing a request that is created by someone else~ (this AC was removed after discussion with product)
- [x] ~Editing a request that was created by someone else~ (this AC was removed after discussion with product)
- [x] ~filtering the request table by agreed upon filters~ (we're working on filter design in another ticket)
- [ ] ~~hiding a domain request~~ (removed as hiding can be achieved with filtering)
- [ ] ~~viewing hidden domain requests~~ (removed as hiding can be achieved with filtering)
- [x] ~viewing domain request history~ (This AC was removed after discussion with product)

## Additional context

The steps below are a general checklist of the process to follow after designs have been created and are ready to share. 

### Phase 1: Team Review (#2455)
*  Share with team for initial approval from PO/product approval
* Set up a **Design/Dev review** meeting with relevant devs to review designs and gather feedback
   * ❗ Smaller design updates will be made as part of this review period. Larger updates need to be a separate ticket. Avoid creating dev tickets **before the design/dev review is complete** unless it's determined that pieces of the work can be started before design has **been finalized.**
* Make any small updates needed as part of the team review period
* (optional) Reshare with PO/Product for final approval if needed

### Phase 2: Feature Kickoff
* Meet with Dev, design, and product to demo approved feature, review any relevant artifacts, and discuss dev tickets

### Links to other issues

Organization model epic: #1772 
Related to: #2063 (lo-fi wireframes)

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 48 will moved forward at noon EST on Day 4 of new sprint (Sprint 49).

**Comment by gabydisarli** [comment]
[Domain request Figma designs](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=5720-52366)
