### ISSUE TITLE
Dev: Send email that announces when domain information has changed

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2307]
### Issue description

We need to send domain managers an announcement when edits have been made to domain information. This includes updates to:

- org name and mailing address
- senior official
- nameservers
- DNSSEC
- security contact

All domain managers for the domain should be CC'd on the email (including the person who made the change).

### Acceptance criteria

- [ ] When a user updates domain information on the following pages via the registrar, an email is sent to all managers for that domain (including the person who made the update): 

  - [ ] - Organization name and mailing address (only domains not in a Portfolio/Organization, which are addressed in #2620 )
  - [ ] - Senior official (only domains not in a Portfolio/Organization, which are addressed in #2620 )
  - [ ] - Nameservers
  - [ ] - DNSSEC
  - [ ] - Security email

- [ ] The email should use content outlined in [this document](https://docs.google.com/document/d/1GOzC-H72QCCR6Dx8bNlf9is7qxF_xibdyd_oGDBhKso/edit).
- [ ] Only send email notifications for DNS changes that take place AFTER the initial DNS name servers are added to the domain. i.e. do not send an email for DNS entries added from the "DNS Needed" state. 
- [ ] Domain managers should be CC'd on the same email rather than sending separate emails.
- [ ] Domain managers page is updated to reflect content changes defined in [this document](https://docs.google.com/document/d/1u-K1yQKb16H3AWj33mH2e1LJme6Ay9dNXMG8isiOXWk/edit#heading=h.5jbqs6f6utm4).

### Links to other issues

- [ ] blocked by #2597 

- [ ] Related content ticket: #2196 
- [ ] Related: #2620

**Comment by Katherine-Osos** [comment]
The related content ticket (#2196) noted that a separate dev ticket should be created for the org model. That doesn't seem necessary; confirm during refinement.

**Comment by abroddrick** [comment]
This one raises a yellow warning flag. We have imported stable dbs into other sandboxes, which includes domain management. If this was added now, changing anything on those domain infos would notify real humans. We need a ticket before this to update documentation with deleting user domain roles after importing from stable (we can't just choose not to import that one table unfortunetly), then probably want to edit the test banner to show if email sending is turned on.

**Comment by abroddrick** [comment]
Also is this meant to block the design review of just the graphics? Could this be it's own milestone?

**Comment by Katherine-Osos** [comment]
@abroddrick Correct on both things! 1) Will apply to non-org (i.e. this ticket can be released before org model is launched) and 2) we should not send emails when the update is initiated via the admin.

cc: @h-m-f-t #2 relates to the discussion we had this morning, so just tagging you for visibility.

**Comment by vickyszuchin** [comment]
Per refinement meeting, @abroddrick will create a dev ticket that will be scoped to preparation for this ticket.

**Comment by Matt-Spence** [comment]
@Katherine-Osos @abroddrick Two questions: 

1. How do we want to handle interactions between multi-recipient emails (emails to more than one person) and the email whitelist? Like, if we have several domain managers, should we block sending the email if *any* of them are not-whitelisted, or just filter the addresses and only send to the whitelisted ones? 
2. Do we want any kind of indication to the user if email sending fails? Perhaps usng the messages API like we do for success/failure of updates?

**Comment by abroddrick** [comment]
Great questions:

**Comment by Katherine-Osos** [comment]
@Matt-Spence For your second question ... no need to display error messaging if the email fails. It's simply a receipt and not the primary action.

That being said, to Alysia's point, let's add a bit of messaging about this update to the **Domain Managers** page.
I DM'd you the new text for that page.

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 54 to the current sprint (sprint 55).
