### ISSUE TITLE
Hi-fidelity Members page and managing members

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2436]
## Issue description

Create hi-fidelity mockups + prototypes to demonstrate how Org model users manage their members across an organization. 
### Acceptance criteria

**Mockups**
- [x] Members page (Org admin and Read-only admin versions)

**Prototypes**
- [x] Admin user manages another admin (include removing)
- [x] Admin user manages another member (include removing)
- [x] Read-only Admin user views a read-only version of a member's page

**Review**
- [x] Review initial designs with design team, product, and dev lead

## Additional context

The steps below are a general checklist of the process to follow after designs have been created and are ready to share. 

### Phase 1: Team Review (#2455)
*  Share with team for initial approval from PO/product approval
* Set up a **Design/Dev review** meeting with relevant devs to review designs and gather feedback
   * ❗ Smaller design updates will be made as part of this review period. Larger updates need to be a separate ticket. Avoid creating dev tickets **before the design/dev review is complete** unless it's determined that pieces of the work can be started before design has **been finalized.**
* Make any small updates needed as part of the team review period
* (optional) Reshare with PO/Product for final approval if needed

### Phase 2: Feature Kickoff
* Meet with Dev, design, and product to demo approved feature, review any relevant artifacts, and discuss dev tickets

## Links to other issues

Team Review: #2455 
Other member management design tickets
* #2437 
* #2438

**Comment by gabydisarli** [comment]
cc: @vickyszuchin I'm pulling this ticket into this sprint to replace the larger member management ticket I mentioned in standup
