### ISSUE TITLE
Hi-fidelity prototype of inviting a new member

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2437]
### Issue description

Create hi-fidelity mockups + prototypes to demonstrate how Org model users manage their members across an organization.

### Acceptance criteria

Prototypes
- [x] (Admin user) inviting a new member
- [ ] (Domain manager user / member with domains) inviting a new domain manager. They will be invited to the org.
- [ ] review initial designs with design team, product, and dev lead

## Additional context

The steps below are a general checklist of the process to follow after designs have been created and are ready to share. 

### Phase 1: Team Review (#2455)
*  Share with team for initial approval from PO/product approval
* Set up a **Design/Dev review** meeting with relevant devs to review designs and gather feedback
   * ❗ Smaller design updates will be made as part of this review period. Larger updates need to be a separate ticket. Avoid creating dev tickets **before the design/dev review is complete** unless it's determined that pieces of the work can be started before design has **been finalized.**
* Make any small updates needed as part of the team review period
* (optional) Reshare with PO/Product for final approval if needed

### Phase 2: Feature Kickoff
* Meet with Dev, design, and product to demo approved feature, review any relevant artifacts, and discuss dev tickets

## Links to other issues

Team Review: #2455 
Other member management design tickets
* #2436 
* #2438

**Comment by AnnaGingle** [comment]
[User flow](https://miro.com/app/board/uXjVNm-Av80=/?moveToWidget=3458764595356958827&cot=14)

**Comment by AnnaGingle** [comment]
[Prototype for inviting a new member](https://www.figma.com/proto/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?page-id=5720%3A52367&node-id=6432-20707&viewport=-20689%2C4454%2C0.33&t=ss0azwDBXBR5n1UM-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6432%3A20707&show-proto-sidebar=1&hotspot-hints=0)
