### ISSUE TITLE
Iterate on member management feature

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2513]
## Issue description

After we've conducted usability testing sessions with our target users. We'll iterate on the member management experience. **Note that we will iterate using lo-fi wireframes for speed and efficiency.**

## Acceptance criteria

- [x] Revise designs from #2436, #2437, #2438 
- [x] Shared with team, and obtained initial team approval

## Additional context

The steps below are a general checklist of the process to follow after designs have been created and are ready to share.

### Phase 1: Team Review (#2456)
Share with team for initial approval from PO/product approval
Set up a Design/Dev review meeting with relevant devs to review designs and gather feedback
❗ Smaller design updates will be made as part of this review period. Larger updates need to be a separate ticket. Avoid creating dev tickets before the design/dev review is complete unless it's determined that pieces of the work can be started before design has been finalized.
Make any small updates needed as part of the team review period
(optional) Reshare with PO/Product for final approval if needed

### Phase 2: Feature Kickoff
Meet with Dev, design, and product to demo approved feature, review any relevant artifacts, and discuss dev tickets

## Links to other issues

- https://github.com/cisagov/manage.get.gov/issues/2511
- https://github.com/cisagov/manage.get.gov/issues/2512
- https://github.com/cisagov/manage.get.gov/issues/2514

**Comment by AnnaGingle** [comment]
:sunrise: Domains/Domain manager assignment needs your review!
In the org model when a domain manager adds a new domain manager who is not a registrar member from the domain page a basic user is created with no additional permissions other than domain management.
[Prototype](https://www.figma.com/proto/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?page-id=5720%3A52362&node-id=7646-33800&viewport=-5234%2C1956%2C0.58&t=IXuvMHzxB0ftks6E-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7646%3A33800&show-proto-sidebar=1)
[Designs](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7646-34582&t=JRS2C5IX64bziuY2-4): [View domain managers](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7646-33800&t=JRS2C5IX64bziuY2-4), [add a new member who is not an org member](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7646-33830&t=JRS2C5IX64bziuY2-4), and [new org member’s profile](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7646-34826&t=JRS2C5IX64bziuY2-4).

The prototype aims to answer this question from the org model agenda: what happens when a domain manager invites a domain manager who isn’t a member?

**Comment by AnnaGingle** [comment]
Iterate on the [member management domain management assignment designs](https://www.figma.com/proto/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?page-id=5720%3A52367&node-id=7453-29291&viewport=-9727%2C3655%2C0.15&t=W1YZtqyrzolmIk6w-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7453%3A29291&show-proto-sidebar=1) based on feedback from last friday.

- [ ] - What happens when a member removes themselves?
- [ ] - What happens when an admin tries to remove themselves but they are the only admin at the org?
- [ ] - Iterate on the [review changes step](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7477-27916&t=xT9hK9VPAp4mCTEa-4) - right now it’s a confirmation modal.

**Comment by gabydisarli** [comment]
@AnnaGingle and I have shared revised designs in the Org model channel. I've placed this ticket in review. [See post here.](https://cisa-corp.slack.com/archives/C07589TAY57/p1724354699823929)

**Comment by gabydisarli** [comment]
These designs have been approved (approvals tracked in [this document](https://docs.google.com/document/d/1S2FchsKOj6vkHEfCtRmET76mhycy8MXwG0LHrmCNlQI/edit#heading=h.chjnejf807te))
