### ISSUE TITLE
Test launches m1 and m2 milestones on AG sandbox

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2615]
### Issue description

We want to temporarily enable org model for some orgs to display the milestones m1 and m2 during using testing. The desire is to have this done on  stable. Thus we should first run through all the steps needed for this on a sandbox so that we can ensure we have all steps covered. Any missing, inaccurate steps should be communicated and documented. Raise questions as needed. After this ticket is completed someone should be able to easily follow your steps and know exactly what to do to setup a portfolio on another sandbox and do testing.
### Acceptance criteria

- [x]  Manually setup the portfolio for Nasa, with real info (use existing domain infos to do this)
- [x] manually setup the suborgs for Nasa.gov, look at the domain info for this info
- [x] add the portfolio to all the correct domains
- [x] update [this section ](https://miro.com/app/board/uXjVKoQVp-I=/?moveToWidget=3458764597523312885&cot=14)of the miro if any other fields are updated that are missing from the above acs
- [ ] manually run the SO script in this sandbox (request access if missing it)
- [x] create a user group for testing
- [x] Turn the portfolio on just for those users in the user group and ensure this user still sees the normal non-org view
- [x] Test that a domain manager for one of this org's domains can be added to the portfolio still sees the normal view
- [x] Add the portfolio to this user's profile and grant them Admin access, verify they still see the normal non-org view
- [x] Add this user to the user group and verify that **now** the org model view shows
- [x] Verify that for the domain this user managers, they can see all org domains and manage the one domain they had access to before. 
- [x] Verify that can see the organization details but only edit organization mailing address. SO should show on the SO tab as readonly.
- [x] Verify that for the domains the user doesn't manage they can see all data in the overview page for the domain but not edit. All fields should be filled in.
- [x] Verify that for the domain the user does manage they can change the suborg as well as all other values 
- [x] document all manual set up steps
- [ ] update the miro and add comments or questions as you go through the above steps and double check if anything is missing. Make sure to write down what fields were used to make portfolio from domain requests/domains (such as org name for sub orgs) etc. We want to be sure to raise any flags if we aren't sure how fields should be mapped between the models. Findings should be shared with the team

### Links to other issues
relates to #2544

**Comment by erinysong** [comment]
Notes while setting up stable for launch:

- How do we want to handle assigning senior officials to portfolios? Currently senior officials do not appear to be connected to our contacts table

**Comment by erinysong** [comment]
[M1/M2 Launch Setup Doc](https://docs.google.com/document/d/1HPKmMKG6j493XmM03gIfJ-C94lS0gKtQAb6mN6O0zSQ/edit?usp=sharing)
