### ISSUE TITLE
Org Model - m1/m2 Launch Checklist

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2617]
### Issue description

The .gov program has decided that the initial launch for public view would allow an org administrator to view and manage their domains for the organization. This will be the first releasable iteration of the org model feature.

This issue will serve as a checklist for launch, presuming all tickets in the **`m1`** and **`m2`** milestones are complete, and is part of the **`m2`** milestone.

### Launch checklist

14+ days out
- [ ] identify first production user, communicate expectations. (Program/product)
- [ ] Re-load sanitized production data on Staging, so it closely reflects reality. (dev)
- [x] #2615 
- [ ] deploy on Staging
- [ ] UAT on Staging (Product)

7 days out
- [ ] Internal "User" Testing session
- [ ] all m1/m2 code deployed to Production (feature flag off)

Day of Launch (cutover)
- [ ] enable m1/m2 feature flag (release)
- [ ] Confirm proper operations (UAT on Prod)
- [ ] customer engaged and using feature.

### Additional context

* Are there any database migration/preload/configuration changes that need to be "coordinated?"
* Design Miro ["Roadmap to Launch"](https://miro.com/app/board/uXjVKnK9iq8=/)
* [m1/m2 launch setup document](https://docs.google.com/document/d/1HPKmMKG6j493XmM03gIfJ-C94lS0gKtQAb6mN6O0zSQ/edit#heading=h.f8v8uy4pmhxm)
* [Team Matrix for m1/m2 launch](https://docs.google.com/spreadsheets/d/1qpXqcTgDzgUQMLPFM2-iBUYJUVVH6l7C-M5zNKq-6u0/edit?gid=822961363#gid=822961363)
* [Launch Candidates](https://docs.google.com/document/d/1cw1vwdLZLHMVzYlMs-stjuYVaQ2fkHiLa-yp5G-o2_0/edit)

### Links to other issues
Related to:
* #2674 
_No response_

**Comment by vickyszuchin** [comment]
@PaulKuykendall, to update description and ACs.

**Comment by gabydisarli** [comment]
@PaulKuykendall Shouldn't this be in m1/m2 release milsetone?

**Comment by katypies** [comment]
Checklist created and tasks being tracked, with appropriate ticket numbers, in the [spreadsheet](https://docs.google.com/spreadsheets/d/1qpXqcTgDzgUQMLPFM2-iBUYJUVVH6l7C-M5zNKq-6u0/edit?gid=562872358#gid=562872358)
