### ISSUE TITLE
(3) [ EPIC ] Figma file updates: Update Registrar/Manage Base Pages

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2780]
**Update from Aug 2024 Audit** 

### Issue description

The audit form Aug 2024 found that the Registar - get.gov/manage/forms base pages do not match production or are missing.  Base pages are mockups of production pages so that designers can use for new feature updates without having to recreate the "base" for every new update. 

Now that the design system component updates have been complete, these pages can be updates.  
Notes on what needs to be updates are made directly in the Figma file. 

The work will be broken up into multiple issues one for each page for easier Figma implementation. The pages with their story links are listed below:
Note that these pages are in the Figma .gov/registar branch labeled - "Jyoti audit updates- Mgn"

- [ ] Mng/Dashboard - [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=1833-17216)
- [ ] Mng/withdraw request - [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3124-32294)
- [ ] Mng/Overview - [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3239-36567)
- [ ] Mng/DNS  - [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3816-38507)
- [ ] Mng/DNS/Name servers -[ Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=1493-95184)
- [ ] Mng/DNS/DNSSEC- [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=939-54742)
- [x] Mng/Organization name and mailing address- [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3826-43000)
- [ ] Mng/Authorizing official- [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3826-44344)
- [ ] Mng/Seniorofficials - [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=8400-24578)
- [ ] Mng/Your Contact information- [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3850-37010)
- [ ] Mng/Security- [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3764-36551)
- [ ] Mng/Domain managers - [Figma page](https://www.figma.com/design/IdnVPju7FTpK0PRsHsB2EA/Jyoti-audit-updates---MngDNS-done?node-id=3266-35070)

### Acceptance criteria
- [ ] Figma Registrar Form base page matches production
- [ ] Update the [Registrar cover page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8193-9457)
- [ ] Update the[ Registrar read me page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8155-37616)
- [ ] Create/update a local "Registrar component" page and centralize local components 
- [ ] Auto-layout is used when possible.
- [ ] Layers are organized and named
- [ ] Design system components and styles are used when possible
- [ ] Changes are made in a Figma branch and are reviewed by another designer
- [ ] Changes are merged

### Additional context
- Try to get these done by the end of the year to make sure audit changes dont become outdated
- Some of the issues will only take a few minutes

### Links to other issues
This work is blocked by all Figma Design System stories. 

Issues in this epic are:

- #2809 
- #2810 
- #2811 
- #2812 
- #2813 
- #2814 
- #2815 
- #2816 
- #2817 
- #2818
- #2819
- #2820

**Comment by joet333** [comment]
Updated to reflect Audit from Aug 2024.

**Comment by Katherine-Osos** [comment]
Closing ticket - no longer how we're tracking the Figma work.
