### ISSUE TITLE
Update onboarding templates and documentation with new access checklist

### ISSUE THREAD

**Issue by katypies** [cisagov/manage.get.gov#2957]
## Issue Description
In #2532 we created an [updated access checklist](https://docs.google.com/spreadsheets/d/1l8HOHVFhDujwvzUP_tzllXuRMDyhbwMLQ6vaCkw48vU/edit?gid=0#gid=0) for the various systems team members need access to, so we can track onboarding and offboarding from those systems more _systematically_ and in an auditable fashion. We now need to audit and update any existing documentation and tickets to ensure that they point to the access checklist.

## Acceptance Criteria

- [ ] Audit Google docs onboarding documentation
- [ ] Make updates to any relevant Google docs
- [ ] Audit existing GitHub ticket templates for onboarding
- [ ] Make updates to GitHub ticket templates
- [ ] Audit existing GitHub wiki and other content for onboarding instructions
- [ ] Make updates to GitHub documentation

## Related Tickets

- Follows #2532
