### ISSUE TITLE
(2982 subissue) Create workshop for testing org model permissions

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2983]
### Issue description

We'll conduct a short workshop to confirm our approach to user permissions within the org model. 

### Acceptance criteria

- [ ] Prep Miro board to use for the workshop
- [ ] Review approach with design/product
- [ ] Create script to use during the workshop
