### ISSUE TITLE
(2982 sub-issue) Update Figma prototypes for usability testing

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2984]
### Issue description

As part of usability testing for the org model, we'll have participants click through some of our Figma prototypes to provide feedback.

### Acceptance criteria

- [ ] Prioritize the Figma prototypes and tasks we want to test
- [ ] Update the corresponding prototypes
- [ ] Ensure the prototypes pair appropriately with the testing scripts

### Links to other issues

This is a sub-issue for https://github.com/cisagov/manage.get.gov/issues/2982
