### ISSUE TITLE
(2982 sub-issue) Create invitation email and scripts for usability testing

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2985]
### Issue description

We need to create an invitation email asking participants to join our testing sessions.

We also need to create a script to guide our testing for the Figma prototypes.

### Acceptance criteria

- [ ] Write content for use in an invitation email (due morning of Oct 30)
- [ ] Write content for the testing script
- [ ] Review all content with design/product

### Links to other issues

This is a sub-issue for https://github.com/cisagov/manage.get.gov/issues/2982
