### ISSUE TITLE
Add Gina to fixtures

### ISSUE THREAD

**Issue by MzBowieFan77** [cisagov/manage.get.gov#3208]
### Sub-issue description

Issue description
Add Gina to the user fixtures

Blocked by https://github.com/cisagov/manage.get.gov/issues/3012 **Not sure if this block carries over**

Acceptance criteria

- [ ] Add Gina to user fixture
- [ ] Run the script add user to sandbox
- [ ] Check with Gina to check that she can log in get to /admin
