### ISSUE TITLE
Dev: Add new FEB questions to org model domain request flow

### ISSUE THREAD

**Issue by katypies** [cisagov/manage.get.gov#3212]
### Sub-issue description

We need to ask some additional questions of Federal Executive Branch (FEB) agencies, to assist OMB in their review of these requests. This sub-issue is for implementation.

### Acceptance criteria

- [ ] Changes described here should be scoped to Org Model/portfolios only, and only for FEB agencies
- [ ] Domain request flow is updated in accordance with [the Figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=14276-2&p=f&t=woSMaK5RljwNmU1o-0)

    - [x] ".gov domain" page: update link and add question regarding compliance with OMB guidance on naming requirements
    - [x] "Purpose of your domain" page:  text field shows conditionally based on selection + additional questions with corresponding text description changes (see note)
    - [x] "Additional details" page: remove single free text field + additional questions with corresponding fields
    - [x] "Requirements for operating a .gov domain" page: add language on required and prohibited activities + change language on checkbox
    - [x] review page
- [ ] Complete the sub-issues

### Additional context

Some of the text boxes are being replaced with a radio button that conditionally shows a text box. These text boxes should maintain the existing variables, so that there aren't multiple variables for essentially the same data or type of data:

- Purpose of your domain - conditions 3a/3b/3c all show a text box that allows for additional explanation of how the domain will be used. Although these use different language, the same purpose variable as what's used for org model and non-org model requests should be used.
- Additional details - use the same variable for the text box as what's used in the additional details text field for the existing flow

### Related issues

- ⛔ Blocked by #2992 
- ⏬ Sub-issue of #2961

**Comment by abroddrick** [comment]
Putting "refinement" on so we know to to double check the ACs in this ticket before work starts on it (as, at the time of writing this, the design is still being worked on which will dictate ACs that should be explicit).

**Comment by katypies** [comment]
This still needs refinement when the design is complete, including possible splitting to include information in DjangoAdmin, exports, and summaries.

**Comment by h-m-f-t** [comment]
@katypies @allly-b Should the new sub-issues (#3494, #3495) be added as A/C (or generalized as "do the sub-issues")?

**Comment by katypies** [comment]
@allly-b @h-m-f-t - updated and went ahead and moved all the dev tickets here, so they share a similar structure. Otherwise, there's a weird distinction in the hierarchy that doesn't fully make sense. In this case, I think the sub-issues are all distinguishable/separable, so can be pointed separately from this (parent) issue. 

@allly-b this parent ticket likely should be pointed since it's actually a distinct set of work. Typically we'd only point it if the sub-issues weren't being pointed, but in this case, the structure lends to having this issue + each sub-issue pointed.

**Comment by katypies** [comment]
Adding @erinysong here to take this one over the finish line! There are two outstanding items from the Design Review that need to be addressed:

1. On the summary page at the end, the section for "Requesting entity" is missing the edit icon and button

2. Purpose page: when selecting "used for a new website", the description text has a couple of typos in the first sentence. Quick visual diff:

<img src="https://github.com/user-attachments/assets/c3713cec-185e-4482-aa56-8d2359f241db" width="400px" />
<br />
<img src="https://github.com/user-attachments/assets/6604fd59-44bf-461b-a7a2-f857f1e672f4" width="400px" />
