### ISSUE TITLE
Design: Review member permissions in registrar (limited scope)

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#3280]
### Sub-issue description

Design should review and compare the output for the member permissions pages within the registrar.

In scope:
- Members table
- Individual member page
- Domain assignments

Out of scope:
- Flow for adding a new member
- Flow for editing a member
- Emails related to adding / removing a member and editing permissions
- Permissions setup in Django admin

### Acceptance criteria

- [x] Designer reviews the member pages described above
- [x] Designer documents any changes needed within the designated slack channel
- [x] Developer determines which changes are small enough to be completed as part of this ticket; then makes those changes
- [x] Developer creates tickets for larger updates that need to be addressed later

### Additional context

**NOTE:** Dev effort on this shouldn't be more than a "2" (2 full work days).

- Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR).
- Anything that would take more than 4 hours to complete alone should be its own ticket. (communicate with Alysia).

Discussions for this design review should take place in this Slack channel: **< insert link to slack channel >**

**Comment by gabydisarli** [comment]
Changes approved!

New tickets created 👇 

[(#3357) Action kebabs for tables: open to the right rather than the left](https://github.com/cisagov/manage.get.gov/issues/3357)

[(#3365) Members table: Change tab order for expand button and make the additional permissions text accessible to screenreaders](https://github.com/cisagov/manage.get.gov/issues/3365)

[(#3396) Change visual indicator on sorted columns for tables](https://github.com/cisagov/manage.get.gov/issues/3396)

[(#3400) Buggy CSS for search bar on the edit member domains page](https://github.com/cisagov/manage.get.gov/issues/3400)
