### ISSUE TITLE
Design: Review workflow for adding/editing members in the registrar, along with related emails

### ISSUE THREAD

**Issue by Katherine-MN** [cisagov/manage.get.gov#3281]
### Sub-issue description

Design should review and compare the output for the member permissions pages within the registrar.

In scope:

- Flow for adding a new member
- Flow for editing a member
- Members table (re-review)
- Individual member page (re-review)
- Related emails that have been completed so far: 
    - [Invitation to join an organization](https://docs.google.com/document/d/1oRY4qg0nOXGSoZb9xlP8dyxurflqi0g_JMWQFZ5-rbE/edit?tab=t.0#heading=h.gjdgxs) ([3019](https://github.com/cisagov/manage.get.gov/issues/3019))
  - [Invitation to manage domains](https://docs.google.com/document/d/18eQRA5QWu5Ct6ICK2-FCZJf9kbbk4LklekRRfb6g9tQ/edit?tab=t.0#heading=h.gjdgxs) ([2960](https://github.com/cisagov/manage.get.gov/issues/2960))
  - [Announce when domain manager invited](https://docs.google.com/document/d/1P8WUqPdggGHjocTCktXgZDcJI-CiUY5sEj5Na2loph0/edit?tab=t.0) ([2370](https://github.com/cisagov/manage.get.gov/issues/2370))
  - [Announce when domain manager removed](https://docs.google.com/document/d/197x7Azy8ITAdwt_QtJnJx0-EfUMJmwd57cx-DGRe6vU/edit?tab=t.0#heading=h.gjdgxs) ([3285](https://github.com/cisagov/manage.get.gov/issues/3285))
  - [Inform admins when new admin has been invited to portfolio](https://docs.google.com/document/d/1MC8TgKx_g8eZ2tGgfe4pQGKKKFMPqHqsCaGjBJNYtME/edit?tab=t.0) ([2416](https://github.com/cisagov/manage.get.gov/issues/2416))
  - [Inform admins when an admin has been removed from portfolio](https://docs.google.com/document/d/1zrVxEzOdU2q_0_o0QQcs8EuLNETuQV2WihQpIyHjetE/edit?tab=t.0#heading=h.iq1fss4x7w3f) ([2416](https://github.com/cisagov/manage.get.gov/issues/2416))

Out of scope:

- Permissions setup in Django admin
- Related emails that have not been implemented yet: 
  - [Inform member when their permissions have changed](https://docs.google.com/document/d/1vpG83Pz9aFdTRIHl3P8U8xTj6s8aG0Die5KyMmw-oUw/edit?tab=t.0#heading=h.gjdgxs) ([3004](https://github.com/cisagov/manage.get.gov/issues/3004))
  - [Inform member when they've been removed from a portfolio](https://docs.google.com/document/d/1aOwh0N6i7S_pLO1-0sKtNJONv7wmjurW8bViaFgzQTE/edit?tab=t.0#heading=h.gjdgxs) ([3288](https://github.com/cisagov/manage.get.gov/issues/3288))

### Acceptance criteria

- [ ] Designer reviews the member pages / emails described above
- [ ] Designer documents any changes needed within the designated slack channel
- [ ] Developer determines which changes are small enough to be completed as part of this ticket; then makes those changes
- [ ] Developer creates tickets for larger updates that need to be addressed later

### Additional context

**NOTE:** Dev effort on this shouldn't be more than a "2" (2 full work days).

- Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR).
- Anything that would take more than 4 hours to complete alone should be its own ticket. (communicate with Alysia).
