### ISSUE TITLE
Design: Review workflow for managing permissions in Django admin and emails

### ISSUE THREAD

**Issue by Katherine-MN** [cisagov/manage.get.gov#3282]
### Sub-issue description

Design should review any added tables/fields to ensure they're displayed logically and consistently with other patterns on the page and are appropriately contextualized for an Analyst.

In scope:
- Django tables related to permissions
  -  Portfolio invitations
  - User portfolio permissions
  - Portfolios (section for "portfolio members")
- Emails related to inviting a member / admin / domain manager (initiated from **Django admin**)
  - [Invitation to join an organization](https://docs.google.com/document/d/1oRY4qg0nOXGSoZb9xlP8dyxurflqi0g_JMWQFZ5-rbE/edit?tab=t.0#heading=h.gjdgxs)
  - [Invitation to manage domains](https://docs.google.com/document/d/18eQRA5QWu5Ct6ICK2-FCZJf9kbbk4LklekRRfb6g9tQ/edit?tab=t.0#heading=h.gjdgxs) 
  - [Announce when domain manager invited](https://docs.google.com/document/d/1P8WUqPdggGHjocTCktXgZDcJI-CiUY5sEj5Na2loph0/edit?tab=t.0) 
  - [Inform admins when new admin has been invited to portfolio](https://docs.google.com/document/d/1MC8TgKx_g8eZ2tGgfe4pQGKKKFMPqHqsCaGjBJNYtME/edit?tab=t.0) 

Out of scope:
- All member/permission functionality within the registrar
- Emails related to inviting a member / admin / domain manager (initiated from **registrar**)

### Acceptance criteria

- [ ] Designer reviews the member pages described above
- [ ] Designer documents any changes needed within the designated slack channel
- [ ] Developer determines which changes are small enough to be completed as part of this ticket; then makes those changes
- [ ] Developer creates tickets for larger updates that need to be addressed later

### Additional context

**NOTE:** Dev effort on this shouldn't be more than a "2" (2 full work days).
- Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR).
- Anything that would take more than 4 hours to complete alone should be its own ticket. (communicate with Alysia).

Discussions for this design review should take place in this Slack channel: **< insert link to slack channel >**

**Comment by Katherine-MN** [comment]
@allly-b I added links to the emails that should be tested as part of this review. Letting you know since it's already marked as "ready."
