### ISSUE TITLE
Section 508 Accessibility Compliance Assessment

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#752]
### Issue Description

Collaborate with a Trusted Tester to complete an initial, then final, assessment of all systems for compliance with Accessibility Requirements.

### Additional Context (optional)

Requests for testing are submitted here: https://dhs.servicenowservices.com/oast

### Issue Links

- [x] Depends on #768 - get.gov info site
- [x] Finalize dev work in #1035 
- [x] Depends on #769 - registrar site
- [x] Depends on #788 - Django Admin

**Comment by PaulKuykendall** [comment]
CDF saved to Google Drive
